#!/usr/bin/env python3
"""
build_kotlin.py — Generates Jetpack Compose ImageVectors from data/icon-data.json

Usage:
  python3 tool/build_kotlin.py [--icons home,search,heart,chat,send2] [--out src/main/kotlin/dev/reicon]

Output (per icon, both weights in one file — mirrors icon.weights in icon-data.json):
  src/main/kotlin/dev/reicon/Home.kt      # object Home { val Outline; val Filled }
  src/main/kotlin/dev/reicon/Reicon.kt    # ReiconWeight enum + ReiconIcon composable (written once, never overwritten)

Mapping:
  fill="currentColor"/"white"/missing -> SolidColor(Color.Black) (tintable via Icon(tint=...))
  fill="none"                          -> fill = null
  stroke="currentColor"                -> stroke = SolidColor(Color.Black)
  stroke-width/cap/join/miterlimit     -> strokeLineWidth/Cap/Join/Miter
  fill-rule="evenodd"                  -> PathFillType.EvenOdd else NonZero
  clip-rule is ignored (no clipPath in ImageVector; Reicon only uses it == fill-rule)
"""

import argparse
import json
import os
import re
import sys
import xml.etree.ElementTree as ET

ROOT = os.path.dirname(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
)
DATA_PATH = os.path.join(ROOT, "data", "icon-data.json")
TOOL_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_OUT = os.path.join(
    os.path.dirname(TOOL_DIR), "src", "main", "kotlin", "dev", "reicon"
)


def to_pascal(kebab: str) -> str:
    parts = re.split(r"[^a-zA-Z0-9]+", kebab)
    out = "".join(p[:1].upper() + p[1:] for p in parts if p)
    if out and out[0].isdigit():
        out = "I" + out
    return out or "Icon"


def parse_paths(code: str):
    wrapped = "<svg xmlns='http://www.w3.org/2000/svg'>" + code + "</svg>"
    root = ET.fromstring(wrapped)
    paths = []
    for el in root.iter():
        if el.tag.endswith("path") or el.tag.endswith("circle"):
            paths.append(el)
    return paths


def el_to_path_args(el) -> str:
    a = el.attrib
    if el.tag.endswith("circle"):
        cx = float(a.get("cx", "12"))
        cy = float(a.get("cy", "12"))
        r = float(a.get("r", "4"))
        d = (
            f"M{cx - r},{cy}a{r},{r} 0 1,0 {2 * r},0a{r},{r} 0 1,0 -{2 * r},0"
        )
    else:
        d = a.get("d", "")

    fill = a.get("fill", None)
    if fill in ("currentColor", "white", "#fff", "#ffffff"):
        fill_k = "fill = SolidColor(Color.Black)"
    elif fill == "none":
        fill_k = "fill = null"
    elif fill is None:
        fill_k = (
            "fill = null"
            if a.get("stroke", "none") not in ("none", None)
            else "fill = SolidColor(Color.Black)"
        )
    else:
        fill_k = "fill = SolidColor(Color.Black)"

    stroke = a.get("stroke", None)
    if stroke in ("currentColor",):
        stroke_k = "stroke = SolidColor(Color.Black)"
    elif stroke is None or stroke == "none":
        stroke_k = "stroke = null"
    else:
        stroke_k = "stroke = SolidColor(Color.Black)"

    sw = a.get("stroke-width", None)
    cap = a.get("stroke-linecap", None)
    join = a.get("stroke-linejoin", None)
    miter = a.get("stroke-miterlimit", None)
    rule = a.get("fill-rule", "nonzero")

    cap_map = {"round": "Round", "butt": "Butt", "square": "Square"}
    join_map = {"round": "Round", "miter": "Miter", "bevel": "Bevel"}

    args = [f'pathData = addPathNodes("{d}")']
    args.append(
        "pathFillType = PathFillType.EvenOdd"
        if rule == "evenodd"
        else "pathFillType = PathFillType.NonZero"
    )
    args.append(fill_k)
    if a.get("fill-opacity", "1") != "1":
        args.append(f"fillAlpha = {a['fill-opacity']}f")
    args.append(stroke_k)
    if sw is not None:
        args.append(f"strokeLineWidth = {sw}f")
    if cap in cap_map:
        args.append(f"strokeLineCap = StrokeCap.{cap_map[cap]}")
    if join in join_map:
        args.append(f"strokeLineJoin = StrokeJoin.{join_map[join]}")
    if miter is not None:
        args.append(f"strokeLineMiter = {miter}f")
    if a.get("stroke-opacity", "1") != "1":
        args.append(f"strokeAlpha = {a['stroke-opacity']}f")
    return "            " + ",\n            ".join(args)


def header_for(uses_cap: bool, uses_join: bool) -> str:
    lines = [
        "// Auto-generated by tool/build_kotlin.py — do not edit.",
        "package dev.reicon",
        "",
        "import androidx.compose.ui.graphics.Color",
        "import androidx.compose.ui.graphics.PathFillType",
        "import androidx.compose.ui.graphics.SolidColor",
    ]
    if uses_cap:
        lines.append("import androidx.compose.ui.graphics.StrokeCap")
    if uses_join:
        lines.append("import androidx.compose.ui.graphics.StrokeJoin")
    lines += [
        "import androidx.compose.ui.graphics.vector.ImageVector",
        "import androidx.compose.ui.graphics.vector.addPathNodes",
        "import androidx.compose.ui.unit.dp",
    ]
    return "\n".join(lines) + "\n"


REICON_KT = """package dev.reicon

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.material3.LocalContentColor
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

enum class ReiconWeight { Outline, Filled }

@Composable
fun ReiconIcon(
    icon: ImageVector,
    contentDescription: String?,
    modifier: Modifier = Modifier,
    size: Dp = 24.dp,
    tint: Color = LocalContentColor.current
) {
    Icon(
        imageVector = icon,
        contentDescription = contentDescription,
        modifier = modifier.size(size),
        tint = tint
    )
}
"""


def generate(icon_filter=None, out_dir=DEFAULT_OUT, copy_to=None):

    with open(DATA_PATH) as f:
        data = json.load(f)

    icons = []
    seen = set()
    for cat_key, cat_data in (data.get("categories") or {}).items():
        for icon_key, icon in (cat_data.get("icons") or {}).items():
            if icon_filter and icon_key not in icon_filter:
                continue
            pascal = to_pascal(icon_key)
            if pascal.lower() in seen:
                pascal += to_pascal(cat_key)
            seen.add(pascal.lower())
            icons.append((icon_key, pascal, icon.get("weights", {})))

    if icon_filter:
        missing = icon_filter - {k for k, _, _ in icons}
        if missing:
            print(f"warning: not found: {sorted(missing)}", file=sys.stderr)

    icons.sort(key=lambda t: t[1])
    print(f"Found {len(icons)} icons")
    os.makedirs(out_dir, exist_ok=True)
    if copy_to:
        os.makedirs(copy_to, exist_ok=True)

    reicon_path = os.path.join(out_dir, "Reicon.kt")
    if not os.path.exists(reicon_path):
        with open(reicon_path, "w") as f:
            f.write(REICON_KT)
        print(f"Wrote {reicon_path}")
    if copy_to and not os.path.exists(os.path.join(copy_to, "Reicon.kt")):
        with open(os.path.join(copy_to, "Reicon.kt"), "w") as f:
            f.write(REICON_KT)
        print("Copied Reicon.kt")

    for kebab, pascal, weights in icons:
        blocks = []
        uses_cap = False
        uses_join = False
        for weight in ("Outline", "Filled"):
            w = weights.get(weight, {})
            code = w.get("code", "")
            if not code:
                continue
            paths = parse_paths(code)
            addpath_calls = []
            for el in paths:
                if el.attrib.get("stroke-linecap") in ("round", "butt", "square"):
                    uses_cap = True
                if el.attrib.get("stroke-linejoin") in ("round", "miter", "bevel"):
                    uses_join = True
                raw = el_to_path_args(el).strip()
                indented = raw.replace("\n            ", "\n                    ")
                addpath_calls.append(
                    "                addPath(\n                    "
                    + indented
                    + "\n                )"
                )
            paths_k = "\n".join(addpath_calls)
            blocks.append(
                f"""    val {weight}: ImageVector
        get() {{
            if (_{weight.lower()} != null) return _{weight.lower()}!!
            _{weight.lower()} = ImageVector.Builder(
                name = "{pascal}{weight}",
                defaultWidth = 24.dp,
                defaultHeight = 24.dp,
                viewportWidth = 24f,
                viewportHeight = 24f
            ).apply {{
{paths_k}
            }}.build()
            return _{weight.lower()}!!
        }}

    private var _{weight.lower()}: ImageVector? = null"""
            )
        body = "\n\n".join(blocks)
        content = f"""{header_for(uses_cap, uses_join)}
object {pascal} {{
{body}
}}
"""
        with open(os.path.join(out_dir, f"{pascal}.kt"), "w") as f:
            f.write(content)
        print(f"  {kebab} -> {pascal}.kt ({'/'.join(weights.keys())})")
        if copy_to:
            with open(os.path.join(copy_to, f"{pascal}.kt"), "w") as f:
                f.write(content)
            print(f"  copied {pascal}.kt")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--icons", default=None)
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--copy-to", default=None)
    args = ap.parse_args()
    filt = set(args.icons.split(",")) if args.icons else None
    generate(filt, args.out, args.copy_to)
